name: Run Integration Tests

on:
  push:
    branches:
      - main  # Run the workflow only on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install MySQL client library
      - name: Install MySQL client library
        run: |
          apt-get install -y mysql-client

      # Run integration test
      - name: Run Integration Test
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pip install mysql-connector-python
          python integration_test.py  # Replace with the name of your integration test file

